### ISSUE TITLE
implement health and readiness endpoints

### ISSUE THREAD

**Issue by attachmentgenie** [grafana/mimir-proxies#10]
Currently i cant find any of the before mentioned endpoints it would help a lot for adding these proxies into a service mesh like HashiCorp Consul

**Comment by fionaliao** [comment]
Hi, which proxy are you using (Datadog or Graphite)?

**Comment by attachmentgenie** [comment]
graphite

**Comment by fionaliao** [comment]
The graphite proxy has a healthcheck endpoint; it starts up an internal server (by default listening on port 8081) and has a  `/healthz` route.

You should be able to see the internal server start up in the logs e.g.

```
level=info ts=2022-09-02T14:06:15.524865115Z msg="Starting internal server" addr=:8081
```

Code reference:

https://github.com/grafana/mimir-proxies/blob/6e1f5ae52026e46ff028c673c2cda40d587baf9f/cmd/graphite-proxy-writes/main.go#L44

https://github.com/grafana/mimir-proxies/blob/6e1f5ae52026e46ff028c673c2cda40d587baf9f/pkg/appcommon/harness.go#L151

https://github.com/grafana/mimir-proxies/blob/6e1f5ae52026e46ff028c673c2cda40d587baf9f/pkg/internalserver/internalserver_handler.go#L50-L53

As an improvement, it would be useful to explain the internal server in the documentation

**Comment by attachmentgenie** [comment]
> As an improvement, it would be useful to explain the internal server in the documentation

That would definitely help,  i saw it popup in the logs, but ignored it sofar. Having the health endpoint on another port than the service port is somewhat inconvenient but i think i might be able to convince consul do advertise the graphite port while checking the internal port.
