### ISSUE TITLE
issue with /api/v2/series

### ISSUE THREAD

**Issue by k-cloudit** [grafana/mimir-proxies#17]
datadog-agent is now sending series on /api/v2/series

and I'm having : 

traceID=72b9299f8cd02c06 sampled=false orgID=fake method=POST uri=/datadog/api/v2/series status=404

Mimir proxies support /api/v1/series but not v2

so now the proxy is not working

**Comment by npazosmendez** [comment]
Hi @k-cloudit . There's ongoing work to support it, thought I can't give any ETA. In the meantime, you may use [this](https://github.com/DataDog/datadog-agent/blob/65ddde6bc4dd051a2eb791f1a212da156e49d6e6/pkg/logs/config/config_keys.go#L263-L264) option in the agent, by setting the env variable `DD_USE_V2_API_SERIES=false`

**Comment by k-cloudit** [comment]
thank you @npazosmendez it fix the issue.
